# Basic
title: 点墨
subtitle: 学习笔记
description: 逢山开路 遇水搭桥
# 头像里面的标题
avatarTitle: tipFiger
# 头像里面的描述
avatarDesc: Python-新世界
url: "http://tipFiger.github.io"

# Comment
comment:
    disqus: tipFiger
    # gitment: xxx // 需要修改 comments.html中的client_id和client_secret
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    # weibo: 5366874726 
    github: tipFiger
    # zhihu: panpanleopard
    # juejin: xxx
    jianshu: 332fe4e135be
    # twitter: 
    mail: xml90524@163.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: xxxx  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: xxxx  
    host: auto  


<<<<<<< HEAD

=======
>>>>>>> e5f60fa0a5b6ab70e94fce1934e0f7e9ac63c203
permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客首页

# Navigation buttons in the front page.s
nav:
    - {title: 时间块, description: archive, url: '/archive'}   
    - {title: 内容块, description: tags, url: '/tags'}      
    - {title: 我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 3
paginate_path: "page/:num/"


